# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci
# IP: The module: 'microblaze_mcs_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c || ORIG_REF_NAME==bd_fc5c} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_microblaze_I_0 || ORIG_REF_NAME==bd_fc5c_microblaze_I_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_rst_0_0 || ORIG_REF_NAME==bd_fc5c_rst_0_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_2/bd_fc5c_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_ilmb_0 || ORIG_REF_NAME==bd_fc5c_ilmb_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_dlmb_0 || ORIG_REF_NAME==bd_fc5c_dlmb_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_4/bd_fc5c_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_dlmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_dlmb_cntlr_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_5/bd_fc5c_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_ilmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_ilmb_cntlr_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_lmb_bram_I_0 || ORIG_REF_NAME==bd_fc5c_lmb_bram_I_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_iomodule_0_0 || ORIG_REF_NAME==bd_fc5c_iomodule_0_0} -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_microblaze_I_0 || ORIG_REF_NAME==bd_fc5c_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_microblaze_I_0_ooc_debug.xdc

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_rst_0_0 || ORIG_REF_NAME==bd_fc5c_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_rst_0_0 || ORIG_REF_NAME==bd_fc5c_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_2/bd_fc5c_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_ilmb_0 || ORIG_REF_NAME==bd_fc5c_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_dlmb_0 || ORIG_REF_NAME==bd_fc5c_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_lmb_bram_I_0_ooc.xdc

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_iomodule_0_0 || ORIG_REF_NAME==bd_fc5c_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_ooc.xdc

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci
# IP: The module: 'microblaze_mcs_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c || ORIG_REF_NAME==bd_fc5c} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_microblaze_I_0 || ORIG_REF_NAME==bd_fc5c_microblaze_I_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_rst_0_0 || ORIG_REF_NAME==bd_fc5c_rst_0_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_2/bd_fc5c_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_ilmb_0 || ORIG_REF_NAME==bd_fc5c_ilmb_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_dlmb_0 || ORIG_REF_NAME==bd_fc5c_dlmb_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_4/bd_fc5c_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_dlmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_dlmb_cntlr_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_5/bd_fc5c_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_ilmb_cntlr_0 || ORIG_REF_NAME==bd_fc5c_ilmb_cntlr_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_lmb_bram_I_0 || ORIG_REF_NAME==bd_fc5c_lmb_bram_I_0} -quiet] -quiet

# IP: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_fc5c_iomodule_0_0 || ORIG_REF_NAME==bd_fc5c_iomodule_0_0} -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_microblaze_I_0 || ORIG_REF_NAME==bd_fc5c_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_microblaze_I_0_ooc_debug.xdc

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_rst_0_0 || ORIG_REF_NAME==bd_fc5c_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_rst_0_0 || ORIG_REF_NAME==bd_fc5c_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_2/bd_fc5c_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_ilmb_0 || ORIG_REF_NAME==bd_fc5c_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_dlmb_0 || ORIG_REF_NAME==bd_fc5c_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_lmb_bram_I_0_ooc.xdc

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_fc5c_iomodule_0_0 || ORIG_REF_NAME==bd_fc5c_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_ooc.xdc

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_mcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
