# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -ruleid {1}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {2}  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.cache/wt [current_project]
set_property parent.project_path D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.sdk/pcdisplay/Debug/pcdisplay.elf
set_property SCOPED_TO_REF microblaze_mcs_0 [get_files -all D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.sdk/pcdisplay/Debug/pcdisplay.elf]
set_property SCOPED_TO_CELLS inst/microblaze_I [get_files -all D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.sdk/pcdisplay/Debug/pcdisplay.elf]
read_verilog -library xil_defaultlib {
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/ClkDiv_50MHz.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/ball_movement.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/board.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/clkdiv_5hz.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/draw_ball.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/draw_score.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/draw_shape.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/final_out.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/paddle1_movement.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/slaveselect.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/spicomponent.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/spiinterface.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/spimaster.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/temp_sensor.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/xvga.v
  D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/new/top_logic.v
}
read_ip -quiet D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci
set_property used_in_implementation false [get_files -all d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_2/bd_fc5c_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/constrs_1/new/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/Study/USA_Graduate/WPI_Graduate_3/17_Fall_Courses/project_final/project_final.srcs/constrs_1/new/Nexys4DDR_Master.xdc]


synth_design -top top_logic -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_logic.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_logic_utilization_synth.rpt -pb top_logic_utilization_synth.pb"
